{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2024-10-28 18:03:05.186101: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
      "2024-10-28 18:03:05.245564: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
      "2024-10-28 18:03:05.246102: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-10-28 18:03:06.066826: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
      "2024-10-28 18:03:07.110175: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\n",
      "NOTE: Using experimental fast data loading logic. To disable, pass\n",
      "    \"--load_fast=false\" and report issues on GitHub. More details:\n",
      "    https://github.com/tensorflow/tensorboard/issues/4784\n",
      "\n",
      "Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all\n",
      "TensorBoard 2.14.0 at http://localhost:6006/ (Press CTRL+C to quit)\n",
      "E1028 18:03:10.525876 140662217352960 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:03:10.780461 140660908746496 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:04:14.661166 140662234138368 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:04:15.095491 140662234138368 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:04:19.844350 140662225745664 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:04:20.102342 140662242531072 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:04:26.948195 140662217352960 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:04:27.353593 140660900353792 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:04:38.619493 140662234138368 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:04:39.065273 140662225745664 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:05:18.880578 140662234138368 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:05:19.146290 140662208960256 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:05:51.223072 140662234138368 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:05:51.345659 140660891961088 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:05:57.920664 140660900353792 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "E1028 18:05:58.044486 140660917139200 _internal.py:97] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 363, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/serving.py\", line 324, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 528, in __call__\n",
      "    return self._app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 569, in wrapper\n",
      "    return wsgi_app(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/security_validator.py\", line 91, in __call__\n",
      "    return self._application(environ, start_response_proxy)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/path_prefix.py\", line 68, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/experiment_id.py\", line 73, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/empty_path_redirect.py\", line 43, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/client_feature_flags.py\", line 55, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/auth_context_middleware.py\", line 38, in __call__\n",
      "    return self._application(environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/backend/application.py\", line 551, in _route_request\n",
      "    return self.exact_routes[clean_path](environ, start_response)\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/werkzeug/wrappers/request.py\", line 190, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/home/anudeep/.local/lib/python3.8/site-packages/tensorboard/plugins/hparams/hparams_plugin.py\", line 122, in get_experiment_route\n",
      "    json_format.MessageToJson(\n",
      "TypeError: MessageToJson() got an unexpected keyword argument 'including_default_value_fields'\n",
      "^C\n"
     ]
    }
   ],
   "source": [
    "!tensorboard --logdir=/home/anudeep/devel/workspace/runs/go1_nn_control"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
